appname: sns-api
port: 8080
env: prod
logger:
  use: zap
  environment: prod
  loglevel: info
  filename: log/app.log
db:
  corpus:
    host: mysql
    port: 3306
    username: mysql
    password: mysql
    database: app
  elasticsearch:
    address: http://localhost:8443
